In [24]:
import numpy as np
d = True

In [29]:
def solve(A,x0,b,n,eps):
    (L,D,R) = decomposition(A)
    x_i = np.copy(x0)
    x_n = np.zeros((len(A),1))
    D_inv = np.linalg.inv(D)
    LR = L+R
    Di_b = np.matmul(D_inv,b)
    DiLR = np.matmul(-1*D_inv,LR)
    counter = 0
    eps = np.linalg.norm(np.full([len(A),1],eps),np.inf)
    if d:
        print("L=\n{}\nD=\n{}\nR=\n{}\n".format(L,D,R))
    while counter < n:    
        for i in range(len(A)):
            for k in range(len(A)):
                if DiLR[i][k] == 0: continue
                if k >= i:
                    x_n[i] = x_n[i] + DiLR[i][k]*x_i[k]
                else:
                    x_n[i] = x_n[i] + DiLR[i][k]*x_n[k]
            x_n[i] = x_n[i] + Di_b[i]
        if d:
            print('x_{}=\n{}'.format(counter+1,x_n))
        if np.linalg.norm(x_i-x_n,np.inf) < eps:
            return x_n
        counter = counter + 1
        x_i = np.copy(x_n)
        x_n[::] = 0
    return x_i

def decomposition(A):
    L = np.tril(A,-1)
    D = np.diagflat(np.diag(A))
    R = np.triu(A,1)
    return (L,D,R)

In [32]:
A = np.array([[8,5,2],[5,9,1],[4,2,7]])
b = np.array([[19],[5],[34]])
x0 = np.array([[1],[-1],[3]], dtype='float64')
n = 1000
solve(A,x0,b,n,1e-17)

L=
[[0 0 0]
 [5 0 0]
 [4 2 0]]
D=
[[8 0 0]
 [0 9 0]
 [0 0 7]]
R=
[[0 5 2]
 [0 0 1]
 [0 0 0]]

x_1=
[[ 2.25      ]
 [-1.02777778]
 [ 3.86507937]]
x_2=
[[ 2.05109127]
 [-1.01339286]
 [ 3.97463152]]
x_3=
[[ 2.01471266]
 [-1.00535498]
 [ 3.99312276]]
x_4=
[[ 2.00506617]
 [-1.0020504 ]
 [ 3.99769087]]
x_5=
[[ 2.00185878]
 [-1.00077609]
 [ 3.99915958]]
x_6=
[[ 2.00069516]
 [-1.00029282]
 [ 3.99968643]]
x_7=
[[ 2.00026141]
 [-1.00011038]
 [ 3.99988216]]
x_8=
[[ 2.00009845]
 [-1.0000416 ]
 [ 3.99995563]]
x_9=
[[ 2.00003709]
 [-1.00001568]
 [ 3.99998328]]
x_10=
[[ 2.00001398]
 [-1.00000591]
 [ 3.9999937 ]]
x_11=
[[ 2.00000527]
 [-1.00000223]
 [ 3.99999763]]
x_12=
[[ 2.00000198]
 [-1.00000084]
 [ 3.99999911]]
x_13=
[[ 2.00000075]
 [-1.00000032]
 [ 3.99999966]]
x_14=
[[ 2.00000028]
 [-1.00000012]
 [ 3.99999987]]
x_15=
[[ 2.00000011]
 [-1.00000004]
 [ 3.99999995]]
x_16=
[[ 2.00000004]
 [-1.00000002]
 [ 3.99999998]]
x_17=
[[ 2.00000002]
 [-1.00000001]
 [ 3.99999999]]
x_18=
[[ 2.00000001]
 [-1.     

array([[ 2.],
       [-1.],
       [ 4.]])