In [1]:
import numpy as np
d = True

In [2]:
def solve(A,x0,b,n, eps):
    (L,D,R) = decomposition(A)
    x_i = np.copy(x0)
    x_n = np.zeros((len(A),1))
    D_inv = np.linalg.inv(D)
    LR = L+R
    Di_b = np.matmul(D_inv,b)
    DiLR = np.matmul(-1*D_inv,LR)
    eps = np.linalg.norm(np.full([len(A),1],eps), np.inf)
    counter = 0
    if d:
        print("L=\n{}\nD=\n{}\nR=\n{}\n".format(L,D,R))
    while counter < n:
        for i in range(len(A)):
            for k in range(len(A)):
                if DiLR[i][k] == 0: continue
                x_n[i] = x_n[i] + DiLR[i][k] * x_i[k]
            x_n[i] = x_n[i] + Di_b[i]
        if d:
            print('x_{}=\n{}'.format(counter+1,x_n))
        if np.linalg.norm(x_i-x_n,np.inf) < eps:
            return x_n
        x_i = np.copy(x_n)
        x_n[:,:] = 0
        counter = counter + 1
    return x_i

def decomposition(A):
    L = np.tril(A,-1)
    D = np.diagflat(np.diag(A))
    R = np.triu(A,1)
    return (L,D,R)

In [3]:
A = np.array([[8,5,2],[5,9,1],[4,2,7]])
b = np.array([[19],[5],[34]])
x0 = np.array([[1],[-1],[3]], dtype='float64')
n = 100
solve(A,x0,b,n,1e-5)

L=
[[0 0 0]
 [5 0 0]
 [4 2 0]]
D=
[[8 0 0]
 [0 9 0]
 [0 0 7]]
R=
[[0 5 2]
 [0 0 1]
 [0 0 0]]

x_1=
[[ 2.25      ]
 [-0.33333333]
 [ 4.57142857]]
x_2=
[[ 1.44047619]
 [-1.20238095]
 [ 3.66666667]]
x_3=
[[ 2.20982143]
 [-0.6521164 ]
 [ 4.37755102]]
x_4=
[[ 1.688185  ]
 [-1.15851757]
 [ 3.78070673]]
x_5=
[[ 2.1538968 ]
 [-0.80240352]
 [ 4.22347074]]
x_6=
[[ 1.82063452]
 [-1.11032831]
 [ 3.85560283]]
x_7=
[[ 2.10505448]
 [-0.88430838]
 [ 4.13401693]]
x_8=
[[ 1.8941885 ]
 [-1.07325437]
 [ 3.90691412]]
x_9=
[[ 2.06905545]
 [-0.93087296]
 [ 4.08139353]]
x_10=
[[ 1.93644722]
 [-1.04740787]
 [ 3.94078916]]
x_11=
[[ 2.04443263]
 [-0.95811392]
 [ 4.04986098]]
x_12=
[[ 1.96135595]
 [-1.0302249 ]
 [ 3.96264247]]
x_13=
[[ 2.02822994]
 [-0.97438025]
 [ 4.030718  ]]
x_14=
[[ 1.97630816]
 [-1.01909641]
 [ 3.97654867]]
x_15=
[[ 2.01779809]
 [-0.98423216]
 [ 4.01899432]]
x_16=
[[ 1.98539652]
 [-1.01199831]
 [ 3.98532457]]
x_17=
[[ 2.0111678 ]
 [-0.99025635]
 [ 4.01177293]]
x_18=
[[ 1.99096699]
 [-1.00751

array([[ 2.00000358],
       [-0.99999696],
       [ 4.00000369]])